### PR TITLE
Updated version number to 1.4.1

### PR DESCRIPTION
**Pull request by hmelman**
Sorry, forgot to do this on the last one.

### CODE REVIEW

**Comment by skurfer** [comment]
As long as we’re still making changes…

* I don’t see `⌃⌘[` listed. It shows everything from history as a searchable results list.
* Can you change `^` to `⌃` on the election navigation shortcuts?

**Comment by skurfer** [comment]
Sorry, I just noticed that you made another commit. That’s something GitHub won’t alert on, so you might want to comment on the pull request after posting changes. Thanks again for the update!

**Comment by hmelman** [comment]
So I made a PR but didn't comment on it and GitHub only notifies if there is a comment, odd. Thanks.

**Comment by skurfer** [comment]
It notifies people when you create the request, just not when you make and push additional commits.

**Pull request merged**
